server:
  port: 8089

spring:
  application:
    name: service-hi
  datasource:
    username: hzero
    password: Q4E%kizUy2#m
    url: jdbc:mysql://192.168.56.201:3306/springboot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5



# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

