server:
  port: 9999

spring:
  application:
    name: springboot_learn
  datasource:
    username: hzero
    password: Q4E%kizUy2#m
    url: jdbc:mysql://192.168.56.201:3306/springboot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

